### ISSUE TITLE
Write python script to download Forex market data

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#55]
Yahoo is the likely source. Looking for daily increments for past 5 years and minute increments for past 5 days.

14-18 currency pairs.

Up to 180 queries (5 for the days, 5 for the years per currency pair) to get started.

Should be one query per currency pair per day after that.

**Comment by jmorgancusick** [comment]
Progress made and added in 6e2f513.

# Current Status

## All components working:
- get all ticker symbols
- make queries to yahoo page
- intervals of day and minute
- can use utc (gmt) timestamps and shift them by days or years
- can json dump to a file to ensure no loss of scrapped data

## TODO
- [x] clean up code: functions, flow comments, etc
- [x] logic for 10 queries per ticker (5 years at day intervals, 5 days at minute intervals) 
- [x] ensure all 56 tickers correct
- [x] connect with dbAPI
- [x] logic for after gather historical data... 1 daily query per ticker for 1 day at minute intervals

**Comment by jmorgancusick** [comment]
Completed as of 4c2cb9b.
